Re-initializing devices if underlying pvc has been changed.
aerospike/aerospike-kubernetes-init pull request #11
Opened 2023-06-05 07:48 UTC by tanmayja

2023-06-05 07:51 UTC, tanmayja commented
TODO: update go.mod with updated aerospike-kubernetes-operator

2023-06-07 10:00 UTC, abhishekdwivedi3060 requested changes

2023-06-07 11:15 UTC, tanmayja commented on pkg/update_pod_status_util.go
dirtyVolumes does not have any dependency on pvcUID, and for sake of keeping it similar with initializedVolumes, we need to make changes in controller code as well.

2023-06-09 07:23 UTC, abhishekdwivedi3060 requested changes

2023-06-09 07:23 UTC, abhishekdwivedi3060 commented on pkg/update_pod_status_util.go
> +				return false, remove(initializedVolumes, initializedVolumes[idx])
We can directly overwrite the index as we not initialising here
initializedVolumes[idx] = fmt.Sprintf("%s@%s", initializedVolumes[idx], pvcUID)

2023-06-09 07:33 UTC, abhishekdwivedi3060 commented on pkg/update_pod_status_util.go
Yeah, at this point `dirtyVolumes` UID is not useful for local-provisioned PVC as we can always cleanup dirtyVolumes. It was just for consistency and future ref

2023-06-09 09:53 UTC, abhishekdwivedi3060 approved these changes

2023-06-15 16:50 UTC, abhishekdwivedi3060 approved these changes

2023-06-27 12:34 UTC, sud82 approved these changes

2023-06-27 12:34 UTC, merged