[KO-259] Validate TLS from config instead of environment var
aerospike/aerospike-kubernetes-init pull request #22
Opened 2023-08-09 06:30 UTC by tanmayja

2023-08-22 08:40 UTC, abhishekdwivedi3060 requested changes

2023-08-22 08:40 UTC, abhishekdwivedi3060 commented on pkg/common-env.go
> +	tlsName, _ := asdbv1.GetServiceTLSNameAndPort(aeroCluster.Spec.AerospikeConfig)
Now we are relying on `GetServiceTLSNameAndPort` to check tls or non-tls type, so should we remove `MY_POD_TLS_ENABLED` env from STS in operator?

2023-08-23 08:35 UTC, abhishekdwivedi3060 approved these changes

2023-09-01 10:34 UTC, sud82 approved these changes

2023-09-01 10:39 UTC, merged