Initial init changes for dynamic config.
aerospike/aerospike-kubernetes-init pull request #27
Opened 2023-12-08 10:54 UTC by tanmayja

2023-12-20 09:37 UTC, abhishekdwivedi3060 approved these changes

2023-12-20 09:37 UTC, abhishekdwivedi3060 commented on cmd/update-conf.go
> +	Long:  `This command updates conf file of aerospike server and updating CR status.`,
```suggestion
	Short: "update conf init functionality",
	Long:  `This command updates conf file of aerospike server and CR status.`,
```

2024-02-02 14:27 UTC, abhishekdwivedi3060 requested changes

2024-02-02 14:27 UTC, abhishekdwivedi3060 commented on pkg/update_pod_status_util.go
> +		if err := initp.k8sClient.Update(ctx, pod); err != nil {
I think we should get the latest object first here to fix object already modified errors also

2024-02-02 14:27 UTC, abhishekdwivedi3060 commented on pkg/update_pod_status_util.go
>  	initp.logger.Info("Updating pod status", "podname", initp.podName)
Fix the logs statements here. Either say `patched/updated pod successfully`  or `updated pod info in Aerospike <name> status.

2024-02-15 08:36 UTC, abhishekdwivedi3060 commented on pkg/update_pod_status_util.go
> +		if err := initp.k8sClient.Update(ctx, pod); err != nil {
Above annotations code will also go inside retry func

2024-02-16 06:24 UTC, abhishekdwivedi3060 approved these changes

2024-02-16 06:24 UTC, abhishekdwivedi3060 commented on go.sum
Why is this removed

2024-03-27 09:19 UTC, abhishekdwivedi3060 approved these changes

2024-04-08 05:36 UTC, sud82 requested changes

2024-04-10 06:17 UTC, sud82 approved these changes

2024-04-10 06:18 UTC, merged